#!/bin/sh
# TODO license etc

set -eu
. "${FORKM_PATH}"/forkm--util

show_help() {
    cat <<EOF
usage: forkm track <branch>...

Track one or more branches as patch branches.

Options:
-q, --quiet        no warnings or info messages
-h, --help     show this message and exit
-V, --version  show version information and exit
EOF
}

if [ $# -eq 0 ]; then
    show_help
    exit 1
fi

branch_list=""
quiet=0
# Parse arguments
while [ $# -gt 0 ]; do
    case $1 in
        -q | --quiet)
            quiet=1
            shift
            ;;
        -h | --help)
            show_help
            exit 0
            ;;
        -V | --version)
            printf "forkm: version %s\n" "${FORKM_VERSION}"
            exit 0
            ;;
        -*) # Invalid options.
            util_error "Invalid flag '$1'"
            show_help
            exit 1
            ;;
        *)
            # Not a flag; add it as one of the branches.
            branch_list="${branch_list} $1"
            shift
            ;;
    esac
done

for branch in ${branch_list}; do
    if [ -z "$(git branch --list -- "${branch}")" ]; then
        util_warn "branch '${branch}' does not exist; ignoring"
        continue
    fi
    read -r name version <<-EOF
	$(util_split_branch_name "${branch}")
	EOF
    if [ -z "${version}" ]; then
        util_warn \
            "branch name '${branch}' lacks version suffix; '-v1' will be implied"
    fi
    git symbolic-ref -- refs/forkm/"${name}" refs/heads/"${branch}"
done
