#!/bin/sh
# forkm: fork management tool
# SPDX-License-Identifier: GPL-3.0-only
#
# Copyright (C) 2025 45mg
#
# This file is part of forkm.
#
# forkm is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 3
# as published by the Free Software Foundation.
#
# forkm is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with forkm. If not, see <http://www.gnu.org/licenses/>.

set -eu
. "${FORKM_PATH}"/forkm--util

show_help() {
    cat <<EOF
usage: forkm track <branch>...

Track one or more branches as patch branches.

Options:
-q, --quiet    no warnings or info messages
-v, --verbose  run with 'set -x'
-h, --help     show this message and exit
-V, --version  show version information and exit
EOF
}

if [ $# -eq 0 ]; then
    show_help
    exit 1
fi

branch_list=""
quiet=0
# Parse arguments
while [ $# -gt 0 ]; do
    case $1 in
        -q | --quiet)
            quiet=1
            shift
            ;;
        -h | --help)
            show_help
            exit 0
            ;;
        -V | --version)
            printf "forkm: version %s\n" "${FORKM_VERSION}"
            exit 0
            ;;
        -v | --verbose)
            set -x
            shift
            ;;
        -*) # Invalid options.
            util_error "Invalid flag '$1'"
            show_help
            exit 1
            ;;
        *)
            # Not a flag; add it as one of the branches.
            branch_list="${branch_list} $1"
            shift
            ;;
    esac
done

for branch in ${branch_list}; do
    if [ -z "$(git branch --list -- "${branch}")" ]; then
        util_warn "branch '${branch}' does not exist; ignoring"
        continue
    fi
    read -r name version <<-EOF
	$(util_split_branch_name "${branch}")
	EOF
    if [ -z "${version}" ]; then
        util_warn \
            "branch name '${branch}' lacks version suffix; '.0' will be implied"
    fi
    git symbolic-ref -- refs/forkm/"${name}" refs/heads/"${branch}"
done
